import { readFileSync } from 'node:fs';
import { expect, test, type Page } from '@playwright/test';
import { gotoMap } from '../map-engine/helpers';

/**
 * Round 10 (verification findings). MAJOR 1: with a route planned, the palette's "Track flight X"
 * (and the aircraft card's SHOW PLANNED PATH, same hand-off) replaces the route, so the flight is
 * drawn and PATHS shows FLIGHT. MAJOR 2: FROM/TO follow the planned route after mount. MAJOR 3 (§8):
 * "London to New York" lists LHR/LGW/STN/LTN/LCY and JFK/EWR/LGA as chips, one click re-plans.
 * /api/flight/AAL401 is stubbed with a fixture (generated by flightDetail from a synthetic DCA→MIA
 * trace), so the test does not depend on a live aircraft; the airport index is bundled.
 */
const status = (page: Page) => page.getByTestId('flight-paths-status');
const panel = (page: Page) => page.locator('section').filter({ has: page.getByRole('heading', { name: 'FLIGHT PATHS' }) });
const FLIGHT = readFileSync('e2e/feature-flight-paths/fixtures/flight-AAL401.json', 'utf8');

async function palette(page: Page, text: string, option: RegExp): Promise<void> {
  await page.keyboard.press('Control+k');
  const dialog = page.getByRole('dialog', { name: 'Command palette' });
  await expect(dialog).toBeVisible();
  await page.keyboard.type(text);
  await expect(dialog.getByRole('option', { name: option })).toBeVisible();
  await page.keyboard.press('Enter');
  await expect(dialog).toBeHidden();
}

test('route planned → palette "Track flight AAL401" replaces the route: flight drawn, FLIGHT tab, no route in the URL', async ({ page, isMobile }) => {
  test.skip(isMobile, 'the command palette is a keyboard flow (desktop)');
  test.setTimeout(150_000);
  await page.route('**/api/flight/AAL401', (r) => r.fulfill({ status: 200, contentType: 'application/json', body: FLIGHT }));
  await gotoMap(page, { params: { layers: '', route: 'DCA-MIA' } });
  await expect(status(page)).toHaveAttribute('data-route', 'DCA-MIA');
  await expect(panel(page)).toBeVisible({ timeout: 30_000 });

  await palette(page, 'AAL401', /Track flight AAL401/);
  await expect(status(page)).toHaveAttribute('data-flight', 'AAL401');
  await expect(status(page)).toHaveAttribute('data-route', '');
  await expect(status(page)).toHaveAttribute('data-layers', /route-flown-track/, { timeout: 60_000 });
  const p = panel(page);
  await expect(p.getByRole('tab', { name: 'FLIGHT' })).toHaveAttribute('aria-selected', 'true');
  await expect(p.getByPlaceholder(/BA117/)).toHaveValue('AAL401');
  await expect.poll(() => new URL(page.url()).searchParams.get('flight')).toBe('AAL401');
  expect(new URL(page.url()).searchParams.get('route')).toBeNull();
});

test('FROM/TO follow a route planned after mount; PLOT keeps the new pair (SYD SCL over LHR-JFK)', async ({ page, isMobile }) => {
  test.skip(isMobile, 'the command palette is a keyboard flow (desktop)');
  test.setTimeout(150_000);
  await gotoMap(page, { params: { route: 'LHR-JFK' } });
  const p = panel(page);
  await expect(p).toBeVisible({ timeout: 30_000 });
  await expect(p.getByLabel('FROM', { exact: true })).toHaveValue('LHR');
  await palette(page, 'SYD SCL', /Plan route SYD → SCL/);
  await expect(status(page)).toHaveAttribute('data-route', 'SYD-SCL');
  await expect(p.getByLabel('FROM', { exact: true })).toHaveValue('SYD');
  await expect(p.getByLabel('TO', { exact: true })).toHaveValue('SCL');
  await p.getByRole('button', { name: /PLOT/ }).click();
  await expect(status(page)).toHaveAttribute('data-route', 'SYD-SCL');
});

test('palette "London to New York" → chooser chips LHR LGW STN LTN LCY and JFK EWR LGA; clicking LGW re-plans LGW-JFK', async ({ page, isMobile }) => {
  test.skip(isMobile, 'the command palette is a keyboard flow (desktop)');
  test.setTimeout(150_000);
  await gotoMap(page);
  await palette(page, 'London to New York', /Plan route LONDON → NEW YORK/);
  await expect(status(page)).toHaveAttribute('data-route', 'LHR-JFK', { timeout: 30_000 });
  const p = panel(page);
  await expect(p.getByLabel('FROM', { exact: true })).toHaveValue('LHR');
  await expect(p.getByLabel('TO', { exact: true })).toHaveValue('JFK');
  const from = p.getByTestId('paths-metro-from');
  const to = p.getByTestId('paths-metro-to');
  const codes = async (g: typeof from) => (await g.getByRole('button').allTextContents()).map((t) => t.trim());
  await expect(from.getByRole('button')).not.toHaveCount(0);
  expect(await codes(from)).toEqual(expect.arrayContaining(['LHR', 'LGW', 'STN', 'LTN', 'LCY']));
  expect(await codes(to)).toEqual(expect.arrayContaining(['JFK', 'EWR', 'LGA']));
  await expect(from.getByRole('button', { name: 'LHR', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await expect(to.getByRole('button', { name: 'JFK', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await from.getByRole('button', { name: 'LGW', exact: true }).click();
  await expect(status(page)).toHaveAttribute('data-route', 'LGW-JFK', { timeout: 30_000 });
  await expect(p.getByLabel('FROM', { exact: true })).toHaveValue('LGW');
  await expect(from.getByRole('button', { name: 'LGW', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await expect(p.getByText('LGW → JFK', { exact: true })).toBeVisible({ timeout: 60_000 });
});
