/**
 * Generates docs/API.md from the typed endpoint catalogue (src/lib/api-catalog.ts), the capability
 * table and the default rate limit: the same sources that render /docs, so the two never drift.
 *
 *   node --experimental-transform-types --import ./tools/ts-loader.mjs tools/gen-api-docs.ts [--check]
 *
 * `--check` exits 1 when docs/API.md is out of date instead of writing it (a unit test does the
 * same check on every `pnpm test`).
 * Owner: pages-docs-privacy-ops.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { API_CATALOG, EXCLUDED_OSIRIS_ROUTES, type ApiEndpoint } from '@/lib/api-catalog';
import { CAPABILITIES, type CapabilitySpec } from '@/lib/capabilities';
import { APP_NAME } from '@/lib/config';
import { DEFAULT_LIMIT } from '@/lib/ratelimit';
import {
  GROUP_META,
  capabilityCondition,
  exampleHref,
  formatCache,
  formatParamType,
  formatRateLimit,
  formatStream,
  groupEndpoints,
  type RateLimitSpec,
} from '@/app/docs/format';

export const API_MD_PATH = fileURLToPath(new URL('../docs/API.md', import.meta.url));

export interface ApiDocsInput {
  catalog: readonly ApiEndpoint[];
  excluded: readonly { path: string; reason: string }[];
  capabilities: Readonly<Record<string, CapabilitySpec>>;
  defaultLimit: RateLimitSpec;
  appName: string;
}

/** Escape a value for a Markdown table cell (pipes and line breaks). */
export function cellText(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/\|/g, '\\|').replace(/\r?\n/g, ' ');
}

/** GitHub's heading anchor algorithm (lower-case, drop punctuation, spaces → hyphens). */
export function githubSlug(heading: string): string {
  return heading
    .trim()
    .toLowerCase()
    .replace(/[^\p{L}\p{N}\s_-]/gu, '')
    .replace(/\s/g, '-');
}

const code = (s: string) => `\`${s}\``;

function endpointMarkdown(e: ApiEndpoint, input: ApiDocsInput): string {
  const rows: [string, string][] = [
    ['Cache', formatCache(e)],
    ['Rate limit', formatRateLimit(e, input.defaultLimit)],
  ];
  const stream = formatStream(e);
  if (stream) rows.push(['Stream', stream]);
  rows.push(['Response', code(e.responseSchema)]);
  if (e.capability) {
    const spec = input.capabilities[e.capability];
    if (spec) rows.push(['Capability', `${code(e.capability)}: ${capabilityCondition(e.capability, spec)}. ${spec.note}.`]);
  }
  rows.push(['Upstreams', e.upstreams.length ? e.upstreams.map(code).join(', ') : 'None: served from this server only']);
  rows.push(['Forwards user input upstream', e.forwardsUserInput ? 'Yes (listed on /privacy)' : 'No']);
  if (e.aliases?.length) rows.push(['Aliases', e.aliases.map(code).join(', ')]);
  if (e.osiris) rows.push(['Compatibility', 'Same path as the OSIRIS endpoint']);
  const href = exampleHref(e);
  if (href) rows.push(['Example', code(`GET ${href}`)]);

  const out = [`### ${code(`${e.method} ${e.path}`)}`, '', e.summary, '', '| | |', '|---|---|'];
  for (const [k, v] of rows) out.push(`| ${k} | ${cellText(v)} |`);
  out.push('');
  if (e.params.length) {
    out.push('| Parameter | In | Type | Required | Description |', '|---|---|---|---|---|');
    for (const p of e.params) {
      const desc = p.example ? `${p.description} (e.g. ${code(p.example)})` : p.description;
      out.push(`| ${code(p.name)} | ${p.in} | ${cellText(formatParamType(p))} | ${p.required ? 'yes' : 'no'} | ${cellText(desc)} |`);
    }
  } else {
    out.push('No parameters.');
  }
  out.push('');
  return out.join('\n');
}

/** Render the full Markdown reference. Pure: same input, same bytes. */
export function renderApiMarkdown(input: ApiDocsInput): string {
  const groups = groupEndpoints(input.catalog);
  const out: string[] = [
    `# ${input.appName} API reference`,
    '',
    '<!-- Generated by tools/gen-api-docs.ts from src/lib/api-catalog.ts. Do not edit by hand. -->',
    '',
    `${input.catalog.length} endpoints, all on the same origin as the app and all usable without an API key. ` +
      'Operator-configured keys only unlock the upgrades listed under [Capabilities](#capabilities); their live state is at `GET /api/health`. ' +
      'The running app renders the same catalogue at `/docs`.',
    '',
    'Regenerate after changing the catalogue: `node --experimental-transform-types --import ./tools/ts-loader.mjs tools/gen-api-docs.ts`.',
    '',
    '## Conventions',
    '',
    '- Feed responses carry `meta` (feed, kind, state, fetchedAt, observedAt, lastGoodAt, stale) and `providers`, one `{ok, count, ms, age_s}` entry per upstream. Observation time and fetch time are separate fields.',
    '- A feed that has never produced data answers `503 source_offline` with `Retry-After: 30` and its provider status, never an empty list pretending to be current.',
    '- Errors are `{error, detail}`: `400 invalid_request`, `429 rate_limited` (with `Retry-After` and `X-RateLimit-Limit`), `500 internal_error` without stack traces.',
    '- GET responses send `Cache-Control: public, s-maxage=TTL, stale-while-revalidate=2×TTL` and weak ETags; `If-None-Match` returns 304. Snapshots served after a failed refresh get an edge TTL of at most 15 s.',
    '- Bulk layers (aircraft, satellites, cameras) are columnar `{fields, rows}`, precompressed with brotli or gzip, and every default response stays under 4 MB.',
    '- Rate limits are per route and per client IP as verified by the deployment\'s proxy; AI routes share one bucket. Timestamps are ISO-8601 UTC.',
    '',
    '## Contents',
    '',
    ...groups.map(([g, list]) => `- [${GROUP_META[g].title}](#${githubSlug(GROUP_META[g].title)}) (${list.length})`),
    '- [Capabilities](#capabilities)',
    '- [Not replicated](#not-replicated)',
    '',
  ];
  for (const [g, list] of groups) {
    out.push(`## ${GROUP_META[g].title}`, '', GROUP_META[g].blurb, '');
    for (const e of list) out.push(endpointMarkdown(e, input));
  }
  out.push(
    '## Capabilities',
    '',
    'Optional upgrades and licence gates, evaluated on the server from environment variables (see `.env.example`). None is required.',
    '',
    '| Capability | Enabled when | Unlocks |',
    '|---|---|---|',
  );
  for (const [id, spec] of Object.entries(input.capabilities)) {
    out.push(`| ${code(id)} | ${cellText(capabilityCondition(id, spec))} | ${cellText(spec.note)} |`);
  }
  out.push('', '## Not replicated', '', `OSIRIS endpoints that ${input.appName} deliberately does not provide, and why.`, '', '| Path | Reason |', '|---|---|');
  for (const r of input.excluded) out.push(`| ${code(r.path)} | ${cellText(r.reason)} |`);
  out.push('');
  return out.join('\n');
}

export function currentInput(): ApiDocsInput {
  return {
    catalog: API_CATALOG as readonly ApiEndpoint[],
    excluded: EXCLUDED_OSIRIS_ROUTES,
    capabilities: CAPABILITIES,
    defaultLimit: DEFAULT_LIMIT,
    appName: APP_NAME,
  };
}

function main(argv: string[]): number {
  const md = renderApiMarkdown(currentInput());
  if (argv.includes('--check')) {
    let existing = '';
    try {
      existing = readFileSync(API_MD_PATH, 'utf8');
    } catch {
      existing = '';
    }
    if (existing === md) return 0;
    console.error('gen-api-docs: docs/API.md is out of date; run without --check to regenerate.');
    return 1;
  }
  writeFileSync(API_MD_PATH, md);
  console.log(`gen-api-docs: wrote docs/API.md (${currentInput().catalog.length} endpoints)`);
  return 0;
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) process.exitCode = main(process.argv.slice(2));
